Repository CodyTolene/pip-apps, pull requests merged in 2025-03, with the labels that each got.

#2 [Game] Pip-Pong
  README.md
  USER/PipPong.js
  USER/PipSnake.js
  USER/_registry.json
Labels: game

#3 [APP] File Explorer
  USER/FileExplorer.js
  USER/_registry.json
Labels: app

#7 [APP][BUG] File Explorer Recurssion Fix
  README.md
  USER/FileExplorer.js
  USER/_registry.json
  package.json
Labels: bug

#11 bring online install version in line with my repo
  USER/StatsDisplay.js
  USER/StatsDisplay/PERKS/ALL/actionboy.json
  USER/StatsDisplay/PERKS/ALL/actiongirl.json
  USER/StatsDisplay/PERKS/ALL/blackwidow.json
  USER/StatsDisplay/PERKS/ALL/cannibal.json
  USER/StatsDisplay/PERKS/ALL/cherchez.json
  USER/StatsDisplay/PERKS/ALL/childatheart.json
  USER/StatsDisplay/PERKS/ALL/comprehension.json
  USER/StatsDisplay/PERKS/ALL/computerwhiz.json
  USER/StatsDisplay/PERKS/ALL/confirmedbachelor.json
  USER/StatsDisplay/PERKS/ALL/educated.json
  USER/StatsDisplay/PERKS/ALL/entomologist.json
  USER/StatsDisplay/PERKS/ALL/fortunefinder.json
  USER/StatsDisplay/PERKS/ALL/foureyes.json
  USER/StatsDisplay/PERKS/ALL/friendofthenight.json
  USER/StatsDisplay/PERKS/ALL/heaveho.json
  USER/StatsDisplay/PERKS/ALL/hunter.json
  USER/StatsDisplay/PERKS/ALL/intensetraining.json
  USER/StatsDisplay/PERKS/ALL/ladykiller.json
  USER/StatsDisplay/PERKS/ALL/missfortune.json
  USER/StatsDisplay/PERKS/ALL/radchild.json
  USER/StatsDisplay/PERKS/ALL/rapidreload.json
  USER/StatsDisplay/PERKS/ALL/retention.json
  USER/StatsDisplay/PERKS/ALL/runngun.json
  USER/StatsDisplay/PERKS/ALL/stealthgirl.json
  USER/StatsDisplay/PERKS/ALL/swiftlearner.json
  USER/StatsDisplay/PERKS/ALL/template.json
  USER/StatsDisplay/PERKS/ALL/weaponhandling.json
  USER/StatsDisplay/PERKS/DISABLED/template.json
  USER/_registry.json
Labels: app

#12 [APP][BUG] Custom Radio v1.1.0 - Fix up files playing randomly
  USER/CustomRadio.js
  USER/_registry.json
Labels: bug, app

#13 [APP][BUG] Stats Display v2.0.1 - Bugfix for the stats app when no perks have been enabled previously
  USER/StatsDisplay.js
  USER/_registry.json
Labels: bug, app
