Repository CodyTolene/pip-apps, pull requests merged in 2025-05, with the labels that each got.

#42 [GAME] Wasteland (DOOM Lite)
  README.md
  USER/Wasteland.js
  USER/Wasteland/F_STEP.wav
  USER/Wasteland/F_STEP_2.wav
  USER/Wasteland/OOF.wav
  registry.json
Labels: game

#44 PipUI+ v1.0.0
  USER_BOOT/PipUiPlus/Special.js
  USER_BOOT/PipUiPlus/Special/a_strength.avi
  USER_BOOT/PipUiPlus/Special/a_strength.json
  USER_BOOT/PipUiPlus/Special/b_perception.avi
  USER_BOOT/PipUiPlus/Special/b_perception.json
  USER_BOOT/PipUiPlus/Special/c_endurance.avi
  USER_BOOT/PipUiPlus/Special/c_endurance.json
  USER_BOOT/PipUiPlus/Special/d_charisma.avi
  USER_BOOT/PipUiPlus/Special/d_charisma.json
  USER_BOOT/PipUiPlus/Special/e_intelligence.avi
  USER_BOOT/PipUiPlus/Special/e_intelligence.json
  USER_BOOT/PipUiPlus/Special/f_agility.avi
  USER_BOOT/PipUiPlus/Special/f_agility.json
  USER_BOOT/PipUiPlus/Special/g_luck.avi
  USER_BOOT/PipUiPlus/Special/g_luck.json
  USER_BOOT/PipUiPlusLoader.js
  registry.json
Labels: app

#51 [APP] Custom Radio v2.2.0
  USER/CustomRadio.js
  USER_BOOT/CustomRadio.js
  registry.json
Labels: bug, enhancement

#52 [APP] Custom Radio - v2.3.0
  USER_BOOT/CustomRadio.js
  registry.json
Labels: bug, enhancement

#55 Re-add theme picker :)
  USER/ThemePicker.js
  USER_BOOT/ThemePickerBootloader.js
  registry.json
Labels: app

#57 [GAME] Pip-Tac-Toe (v1.1.0)
  USER/PipTacToe.js
  registry.json
Labels: game

#58 [GAME] Piptris (v1.1.0)
  .scripts/minify-folders.js
  .scripts/minify.js
  README.md
  USER/Piptris.js
  minified/USER/Piptris.js
  minified/USER_BOOT/.gitkeep
  package-lock.json
  package.json
  registry.json
Labels: bug/fix, enhancement, game

#59 [GAME/APP] Minify Custom Radio, File Explorer, and Piptris (updated)
  .scripts/minify-folders.js
  .scripts/minify.js
  README.md
  USER/CustomRadio.js
  USER/FileExplorer.js
  USER/Piptris.js
  min/USER/CustomRadio.js
  min/USER/FileExplorer.js
  min/USER/Piptris.js
  min/USER_BOOT/.gitkeep
  minified/USER/Piptris.js
  registry.json
Labels: enhancement, game, app

#63 [GAME] Pip-Tac-Toe v1.1.2 (Add minified file)
  USER/PipTacToe.min.js
  registry.json
Labels: game

#66 [GAME] Piptris v2.1.0
  USER/Piptris.js
  USER/Piptris.min.js
  registry.json
Labels: bug/fix, enhancement, game

#67 Custom radio v2.5.0
  USER/CustomRadio.js
  USER_BOOT/CustomRadio.js
  USER_BOOT/CustomRadio.min.js
  docs/scripts/commands.js
  registry.json
Labels: app

#72 Quick build updates
  .github/workflows/build-apps.yml
Labels: enhancement
