Repository CodyTolene/pip-apps, pull requests merged in 2025-04, with the labels that each got.

#16 [GAMES] Pip-Pong & Pip-Snake improvements.
  USER/PipPong.js
  USER/PipSnake.js
  USER/_registry.json
  docs/loader.css
Labels: game

#18 Ui_color_theme
  USER/ThemePicker.js
  USER_BOOT/ui_color.js
  registry.json
Labels: app

#17 Revamp UX + New Features + Bootloader
  .github/images/pip-app-loader.png
  .github/pull_request_template.md
  .prettierignore
  README.md
  USER/PipPong.js
  USER/PipSnake.js
  USER/ThemePicker.js
  USER/_registry.json
  USER_BOOT/ThemePicker.js
  docs/index.html
  docs/loader.css
  docs/loader.js
  docs/scripts/commands.js
  docs/scripts/elements.js
  docs/scripts/loader.js
  registry.json
Labels: documentation, enhancement

#19 [APP] Fix description for Theme Picker
  registry.json
Labels: documentation

#21 Game/app documentation cleanup
  USER/StatsDisplay.js
  USER/ThemePicker.js
  USER_BOOT/ThemePicker.js
Labels: documentation

#25 Official Update - Remove Theme Picker & Disable Stats Display
  USER/ThemePicker.js
  USER_BOOT/.gitkeep
  USER_BOOT/ThemePicker.js
  registry.json
Labels: bug

#32 [GAME] Vault Breaker Update v1.0.1
  USER/VaultBreaker.js
  registry.json
Labels: enhancement

#36 Stats Display 2.2.2: bugfix for perk select screen
  USER/StatsDisplay.js
  registry.json
Labels: bug
